heat_template_version: 2015-04-30

description: >
  Creates a port on the monitoring network.

parameters:
  MonitoringNetName:
    description: Name of the monitoring neutron network
    default: monitoring
    type: string
  PortName:
    description: Name of the port
    default: ''
    type: string
  ControlPlaneIP: # Here for compatability with noop.yaml
    description: IP address on the control plane
    default: ''
    type: string
  FixedIPs:
    description: >
        Control the IP allocation for the VIP port. E.g.
        [{'ip_address':'1.2.3.4'}]
    default: []
    type: json
  IPPool: # Here for compatibility with from_pool.yaml
    default: {}
    type: json
  NodeIndex: # Here for compatibility with from_pool.yaml
    default: 0
    type: number

resources:

  MonitoringPort:
    type: OS::Neutron::Port
    properties:
      network: {get_param: MonitoringNetName}
      name: {get_param: PortName}
      fixed_ips: {get_param: FixedIPs}
      replacement_policy: AUTO

outputs:
  ip_address:
    description: monitoring network IP
    value: {get_attr: [MonitoringPort, fixed_ips, 0, ip_address]}
  ip_address_uri:
    description: monitoring network IP with brackets suitable for a URL
    value:
          list_join:
          - ''
          - - '['
            - {get_attr: [MonitoringPort, fixed_ips, 0, ip_address]}
            - ']'
  ip_subnet:
    # FIXME: this assumes a 2 digit subnet CIDR (need more heat functions?)
    description: IP/Subnet CIDR for the monitoring network IP
    value:
          list_join:
            - ''
            - - {get_attr: [MonitoringPort, fixed_ips, 0, ip_address]}
              - '/'
              - {get_attr: [MonitoringPort, subnets, 0, cidr, -2]}
              - {get_attr: [MonitoringPort, subnets, 0, cidr, -1]}
