heat_template_version: 2015-04-30

description: >
  Software Config to drive os-net-config with 2 bonded nics on a bridge
  with VLANs attached for the compute role.

parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal API network
    type: string
  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage mgmt network
    type: string
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  MonitoringIpSubnet:
    default: ''
    description: IP address/subnet on the monitoring network
    type: string
  ManagementIpSubnet: # Only populated when including environments/network-management.yaml
    default: ''
    description: IP address/subnet on the management network
    type: string
  BondInterfaceCtlPlaneOptions:
    default: 'miimon=100 mode=6'
    description: The bonding_options string for the bonding interface on control
                 plane. Set things like miimon=100, mode=6 and/or other arguments 
                 using this option.
    type: string
  BondInterfaceDataPlaneOptions:
    default: 'miimon=100 mode=4'
    description: The bonding_options string for the bonding interface on data
                 plane. Set things like miimon=100, mode=4 and/or other arguments
                 using this option.
    type: string
  BondInterfaceOvsOptions:
    default: 'bond_mode=active-backup'
    description: The ovs_options string for the bond interface. Set things like
                 lacp=active and/or bond_mode=balance-slb using this option.
                 This parameter has been deprecated in this environment.
    type: string
  InternalApiNetworkVlanID:
    default: 20
    description: Vlan ID for the internal_api network traffic.
    type: number
  StorageNetworkVlanID:
    default: 30
    description: Vlan ID for the storage network traffic.
    type: number
  StorageMgmtNetworkVlanID:
    default: 40
    description: Vlan ID for the storage mgmt network traffic.
    type: number
  TenantNetworkVlanID:
    default: 50
    description: Vlan ID for the tenant network traffic.
    type: number
  ManagementNetworkVlanID:
    default: 60
    description: Vlan ID for the management network traffic.
    type: number
  MonitoringNetworkVlanID:
    default: 70
    description: Vlan ID for the monitoring network traffic.
    type: number
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  ControlPlaneDefaultRoute: # Override this via parameter_defaults
    description: The default route of the control plane network.
    type: string
  DnsServers: # Override this via parameter_defaults
    default: []
    description: A list of DNS servers (2 max for some implementations) that will be added to resolv.conf.
    type: comma_delimited_list
  EC2MetadataIp: # Override this via parameter_defaults
    description: The IP address of the EC2 metadata server.
    type: string

resources:
  OsNetConfigImpl:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        os_net_config:
          network_config:
            -
              type: ovs_bridge
              name: br-ctlplane
              use_dhcp: false
              dns_servers: {get_param: DnsServers}
              addresses:
                -
                  ip_netmask:
                    list_join:
                      - '/'
                      - - {get_param: ControlPlaneIp}
                        - {get_param: ControlPlaneSubnetCidr}
              routes:
                -
                  ip_netmask: 169.254.169.254/32
                  next_hop: {get_param: EC2MetadataIp}
                -
                  default: true
                  next_hop: {get_param: ControlPlaneDefaultRoute}
              members:
                -
                  type: linux_bond
                  name: bond0
                  bonding_options: {get_param: BondInterfaceCtlPlaneOptions}
                  members:
                    -
                      type: interface
                      name: em3
                    -
                      type: interface
                      name: em4
                -
                  type: vlan
                  vlan_id: {get_param: ManagementNetworkVlanID}
                  device: bond0
                  use_dhcp: false
                  dns_servers: {get_param: DnsServers}
                  addresses:
                    - ip_netmask: {get_param: ManagementIpSubnet}
                -
                  type: vlan
                  vlan_id: {get_param: InternalApiNetworkVlanID}
                  device: bond0
                  use_dhcp: false
                  addresses:
                    - ip_netmask: {get_param: InternalApiIpSubnet}
                -
                  type: vlan
                  vlan_id: {get_param: MonitoringNetworkVlanID}
                  device: bond0
                  use_dhcp: false
                  addresses:
                    - ip_netmask: {get_param: MonitoringIpSubnet}
            -
              type: ovs_bridge
              name: {get_input: bridge_name}
              members:
                -
                  type: linux_bond
                  name: bond1
                  bonding_options: {get_param: BondInterfaceDataPlaneOptions}
                  members:
                    -
                      type: interface
                      name: em1
                    -
                      type: interface
                      name: em2
                -
                  type: vlan
                  vlan_id: {get_param: StorageNetworkVlanID}
                  device: bond1
                  addresses:
                    - ip_netmask: {get_param: StorageIpSubnet}
                -
                  type: vlan
                  vlan_id: {get_param: StorageMgmtNetworkVlanID}
                  device: bond1
                  addresses:
                    - ip_netmask: {get_param: StorageMgmtIpSubnet}
                -
                  type: vlan
                  vlan_id: {get_param: TenantNetworkVlanID}
                  device: bond1
                  addresses:
                    - ip_netmask: {get_param: TenantIpSubnet}


outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value: {get_resource: OsNetConfigImpl}
