#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist)
  #OS::TripleO::BlockStorage::Net::SoftwareConfig:
  #  nic-configs/controller.yaml
  OS::TripleO::Compute::Net::SoftwareConfig:
    nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig:
    nic-configs/controller.yaml
  #OS::TripleO::ObjectStorage::Net::SoftwareConfig:
  #  nic-configs/controller.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig:
    nic-configs/ceph-storage.yaml

parameter_defaults:
  CloudDomain: 'zone1.region2.ncloud.com'
  # This section is where deployment-specific configuration is done
  # Customize the IP subnets to match the local environment
  ManagementNetCidr: 10.253.3.0/24
  MonitoringNetCidr: 10.253.4.0/24
  InternalApiNetCidr: 10.253.5.0/24
  TenantNetCidr: 10.252.1.0/24
  StorageNetCidr: 10.252.2.0/24
  StorageMgmtNetCidr: 10.252.3.0/24
  ExternalNetCidr: 1.93.65.0/24
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '24'
  # Customize the IP ranges on each network to use for static IPs and VIPs
  ManagementAllocationPools: [{'start': '10.253.3.11', 'end': '10.253.3.150'}]
  MonitoringAllocationPools: [{'start': '10.253.4.11', 'end': '10.253.4.150'}]
  InternalApiAllocationPools: [{'start': '10.253.5.11', 'end': '10.253.5.150'}]
  TenantAllocationPools: [{'start': '10.252.1.11', 'end': '10.252.1.150'}]
  StorageAllocationPools: [{'start': '10.252.2.11', 'end': '10.252.2.150'}]
  StorageMgmtAllocationPools: [{'start': '10.252.3.11', 'end': '10.252.3.150'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '1.93.65.5', 'end': '1.93.65.8'}]
  # Gateway router for the external network
  ExternalInterfaceDefaultRoute: 1.93.65.1
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 10.253.2.4
  # Generally the IP of the Undercloud
  EC2MetadataIp: 10.253.2.4
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["8.8.8.8","8.8.4.4"]
  # Customize the VLAN IDs to match the local environment
  ManagementNetworkVlanID: 103
  MonitoringNetworkVlanID: 104
  InternalApiNetworkVlanID: 105
  TenantNetworkVlanID: 106
  StorageNetworkVlanID: 107
  StorageMgmtNetworkVlanID: 108
  ExternalNetworkVlanID: 121
  # Set to empty string to enable multiple external networks or VLANs
  NeutronExternalNetworkBridge: "''"
  
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  BondInterfaceCtlPlaneOptions: "miimon=100 mode=6"
  BondInterfaceDataPlaneOptions: "miimon=100 mode=4"
